spring:
  profiles:
    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  security:
    user:
      name: admin
      password: admin
server:
  port: 8889


# mybatis
mybatis:
  type-aliases-package: com.ccunix.springbootsecurity.**.domain
  mapper-locations: mapper/**/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

ccunix:
  # 名称
  name: ccunix
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ccunix/uploadPath，Linux配置 /home/ccunix/uploadPath）
  profile: D:/ccunix/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
