spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin
server:
  port: 8889


# mybatis
mybatis:
  type-aliases-package: com.ccunix.springbootsecurity.**.domain
  mapper-locations: mapper/**/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
